/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.ontheair.Database;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jakubwawak
 */
public class login_window extends javax.swing.JDialog {

    /**
     * Creates new form login_window
     */
    Database database;
    
    public login_window(javax.swing.JDialog parent, boolean modal,Database database) {
        super(parent, modal);
        this.database = database;
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(parent);
        getContentPane().setBackground(Color.ORANGE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_login = new javax.swing.JTextField();
        label_cancel = new javax.swing.JLabel();
        label_login = new javax.swing.JLabel();
        field_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        field_login.setBackground(new java.awt.Color(0, 0, 0));
        field_login.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        field_login.setForeground(new java.awt.Color(255, 255, 255));
        field_login.setText("login");

        label_cancel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        label_cancel.setForeground(new java.awt.Color(255, 255, 255));
        label_cancel.setText("Cancel");
        label_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_cancelMouseClicked(evt);
            }
        });

        label_login.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setText("Log in");
        label_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_loginMouseClicked(evt);
            }
        });

        field_password.setBackground(new java.awt.Color(0, 0, 0));
        field_password.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        field_password.setForeground(new java.awt.Color(255, 255, 255));
        field_password.setText("jPasswordField1");
        field_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_passwordFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_login)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(field_password, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(field_login, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(label_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_login)
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(129, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_passwordFocusGained
        field_password.setText("");
    }//GEN-LAST:event_field_passwordFocusGained

    private void label_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_cancelMouseClicked
        dispose();
    }//GEN-LAST:event_label_cancelMouseClicked

    private void label_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_loginMouseClicked
        try {
            if ( database.log_ota_user(field_login.getText(), field_password.getText()) > 0 ){
                database.log_ota_user(field_login.getText(), field_password.getText());
                dispose();
            }
        } catch (SQLException ex) {
            field_login.setText("Program error");
            field_login.setEnabled(false);
            field_password.setEnabled(false);
            label_login.setText("Error");
            label_login.setEnabled(false);
        }
    }//GEN-LAST:event_label_loginMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_login;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JLabel label_cancel;
    private javax.swing.JLabel label_login;
    // End of variables declaration//GEN-END:variables
}
