/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.radioplayer.Boombox;
import com.jakubwawak.radioplayer.RadioPlayer;
import com.jakubwawak.radioplayer.RadioStation;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *Object creating main window
 * @author jakubwawak
 */
public class main_window2 extends javax.swing.JFrame {

    /**
     * Creates new form main_window2
     */
    String version;
    Boombox boombox;
    RadioPlayer player;
    
    public main_window2(String version) {
        initComponents();
        boombox = new Boombox();
        load_window();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.BLACK);
        setVisible(true);
    }
    
    
    /**
     * Function for loading window components
     */
    void load_window(){
        label_version.setText(version);
        label_error.setVisible(false);
        label_radiostation.setText(boombox.picked);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        label_radiostation = new javax.swing.JLabel();
        label_selected = new javax.swing.JLabel();
        button_play = new javax.swing.JButton();
        label_version = new javax.swing.JLabel();
        label_error = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menu_presets = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OnTheAir");

        label_radiostation.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label_radiostation.setForeground(new java.awt.Color(255, 255, 255));
        label_radiostation.setText("RADIOSTATION NAME");
        label_radiostation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_radiostationMouseClicked(evt);
            }
        });

        label_selected.setForeground(new java.awt.Color(255, 255, 255));
        label_selected.setText("Selected:");

        button_play.setBackground(new java.awt.Color(255, 255, 255));
        button_play.setForeground(new java.awt.Color(0, 0, 0));
        button_play.setText("Play");
        button_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_playActionPerformed(evt);
            }
        });

        label_version.setBackground(new java.awt.Color(255, 255, 255));
        label_version.setForeground(new java.awt.Color(255, 255, 255));
        label_version.setText("v1.0.0XX");

        label_error.setForeground(new java.awt.Color(255, 0, 51));
        label_error.setText("Player error");

        jMenuBar2.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));

        jMenu3.setText("Actions");

        menu_presets.setText("Presets");
        menu_presets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_presetsActionPerformed(evt);
            }
        });
        jMenu3.add(menu_presets);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_error, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(label_version))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_selected, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_radiostation, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_version)
                    .addComponent(label_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_selected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_radiostation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_play, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Function for getting selected RadioStation
     * @return RadioStation
     */
    RadioStation get_selected_station(){
        System.out.println(label_radiostation.getText());
        return boombox.get_radio(label_radiostation.getText());
    }
    private void label_radiostationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_radiostationMouseClicked
        if ( player != null){
            player.stop();
            button_play.setText("Play");
        }
        System.out.println("Radiostation change invoked");
        new radiostation_picker_window(this,true,boombox);
        if ( !boombox.picked.equals("") ){
            label_radiostation.setText(boombox.picked);
            label_radiostation.setVerticalAlignment(JLabel.CENTER);
        }
    }//GEN-LAST:event_label_radiostationMouseClicked

    private void button_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_playActionPerformed
        String state = button_play.getText();
        label_error.setVisible(false);
        RadioStation selected_radio = get_selected_station();
        switch(state){
            case "Play":
                try{
                    player = new RadioPlayer(selected_radio);
                    Thread player_thread = new Thread(player);
                    player_thread.start();
                    button_play.setText("Stop");
                    button_play.setVerticalAlignment(JLabel.CENTER);
                }catch(Exception e){
                    label_error.setVisible(true);
                }
                
                break;
            case "Stop":
                player.stop();
                player = null;
                button_play.setText("Play");
                break;
            default:
                System.out.println("Błąd");
                break;
        }
    }//GEN-LAST:event_button_playActionPerformed

    private void menu_presetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_presetsActionPerformed
        new myaccount_window(this,true,boombox);
    }//GEN-LAST:event_menu_presetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_play;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel label_error;
    private javax.swing.JLabel label_radiostation;
    private javax.swing.JLabel label_selected;
    private javax.swing.JLabel label_version;
    private javax.swing.JMenuItem menu_presets;
    // End of variables declaration//GEN-END:variables
}
