/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.radioplayer.Boombox;
import com.jakubwawak.radioplayer.RadioPlayer;
import com.jakubwawak.radioplayer.RadioStation;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javazoom.jl.decoder.JavaLayerException;

/**
 *Main window object
 * @author x
 */
public class main_window extends javax.swing.JFrame {

    /**
     * Creates new form main_window
     */
    String version = "v.1.0.0A1";
    final String BGC_SRC = "bcg.jpg";
    Background_Panel panel;
    Boombox boombox;
    RadioPlayer player;
    
    public main_window() throws IOException {
        panel = new Background_Panel(new ImageIcon(BGC_SRC).getImage());
        boombox = new Boombox();
        initComponents();
        load_window();
        this.getContentPane().add(panel);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * Function for loading default window content
     */
    void load_window(){
        label_version.setText(version);
        load_default_presets();
    }
    
    /**
     * Function for loading data to ComboBox model
     */
    void load_default_presets(){
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        dcm.addAll(boombox.list_of_names());
        combobox_presets.setModel(dcm);
        combobox_presets.setSelectedIndex(0);
    }
    
    /**
     * Function for getting selected RadioStation
     * @return RadioStation
     */
    RadioStation get_selected_station(){
        String title = combobox_presets.getSelectedObjects().toString();
        return boombox.get_radio(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox_presets = new javax.swing.JComboBox<>();
        button_play = new javax.swing.JButton();
        label_version = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OnTheAir");

        combobox_presets.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        combobox_presets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combobox_presets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_presetsActionPerformed(evt);
            }
        });

        button_play.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        button_play.setText("Play");
        button_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_playActionPerformed(evt);
            }
        });

        label_version.setText("v.1.0.0");

        jMenu1.setText("Actions");

        jMenuItem1.setText("Log In");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Presets");

        jMenuItem2.setText("Manage");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(combobox_presets, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(button_play, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_version)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(combobox_presets, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_play, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_version)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_playActionPerformed
        String state = button_play.getText();
        RadioStation selected_radio = get_selected_station();
        try{
            switch(state){
                case "Play":
                    player = new RadioPlayer(selected_radio);
                    player.play();
                    button_play.setText("Stop");
                    break;
                case "Stop":
                    player.stop();
                    player = null;
                    button_play.setText("Play");
                    break;
                default:
                    System.out.println("Błąd");
                    break;
            }
        } catch (IOException ex) {
            System.out.println(ex.toString());
        } catch (JavaLayerException ex) {
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_button_playActionPerformed

    private void combobox_presetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_presetsActionPerformed
        
    }//GEN-LAST:event_combobox_presetsActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_play;
    private javax.swing.JComboBox<String> combobox_presets;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel label_version;
    // End of variables declaration//GEN-END:variables
}
