/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.radioplayer.Boombox;
import com.jakubwawak.radioplayer.RadioPlayer;
import com.jakubwawak.radioplayer.RadioStation;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *Main window object
 * @author x
 */
public class main_window extends javax.swing.JFrame {

    /**
     * Creates new form main_window
     */
    String version = "v.1.0.0B1";
    final String BGC_SRC = "bcg.jpg";
    Background_Panel panel;
    Boombox boombox;
    RadioPlayer player;
    
    public main_window() throws IOException {
        panel = new Background_Panel(new ImageIcon(BGC_SRC).getImage());
        boombox = new Boombox();
        this.setUndecorated(true);
        initComponents();
        load_window();
        this.getContentPane().add(panel);
        this.setLocationRelativeTo(null);
        locate_window();
        setVisible(true);
    }
    
    /**
     * Function for loading default window content
     */
    void load_window(){
        label_version.setText(version);
        load_default_presets();
    }
    
    /**
     * Function for locating window on screen
     */
    void locate_window(){
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
            Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
            int x = (int) rect.getMaxX() - this.getWidth();
            int y = 23;
            this.setLocation(x, y);
            this.setVisible(true);
    }
    
    /**
     * Function for loading data to ComboBox model
     */
    void load_default_presets(){
        label_radiostationname.setText(boombox.list_of_names().get(0));
    }
    
    /**
     * Function for getting selected RadioStation
     * @return RadioStation
     */
    RadioStation get_selected_station(){
        System.out.println("Selected radio: "+label_radiostationname.getText());
        return boombox.get_radio(label_radiostationname.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_version = new javax.swing.JLabel();
        label_radiostationname = new javax.swing.JLabel();
        label_play = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_closeprogram = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OnTheAir");

        label_version.setFont(new java.awt.Font("Bodoni 72", 0, 13)); // NOI18N
        label_version.setText("v.1.0.0");
        label_version.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_versionMouseClicked(evt);
            }
        });

        label_radiostationname.setFont(new java.awt.Font("Bodoni 72", 0, 36)); // NOI18N
        label_radiostationname.setForeground(new java.awt.Color(255, 255, 255));
        label_radiostationname.setText("RadioStation Name");
        label_radiostationname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_radiostationnameMouseClicked(evt);
            }
        });

        label_play.setFont(new java.awt.Font("Bodoni 72", 0, 36)); // NOI18N
        label_play.setForeground(new java.awt.Color(255, 255, 255));
        label_play.setText("Play");
        label_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_playMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bodoni 72", 0, 18)); // NOI18N
        jLabel1.setText("My Account");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        label_closeprogram.setFont(new java.awt.Font("Bodoni MT", 0, 11)); // NOI18N
        label_closeprogram.setForeground(new java.awt.Color(255, 255, 255));
        label_closeprogram.setText("Close program");
        label_closeprogram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeprogramMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_radiostationname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(label_play, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_version)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_closeprogram))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_closeprogram)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_radiostationname)
                    .addComponent(label_play))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_version))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_playMouseClicked
        String state = label_play.getText();
        RadioStation selected_radio = get_selected_station();
        switch(state){
            case "Play":
                player = new RadioPlayer(selected_radio);
                Thread player_thread = new Thread(player);
                player_thread.start();
                label_play.setText("Stop");
                break;
            case "Stop":
                player.stop();
                player = null;
                label_play.setText("Play");
                break;
            default:
                System.out.println("Błąd");
                break;
        }
    }//GEN-LAST:event_label_playMouseClicked

    private void label_radiostationnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_radiostationnameMouseClicked
        if ( player != null){
            player.stop();
            label_play.setText("Play");
        }
        System.out.println("Radiostation change invoked");
        new radiostation_picker_window(this,true,boombox);
        if ( !boombox.picked.equals("") ){
            label_radiostationname.setText(boombox.picked);
        }
        
    }//GEN-LAST:event_label_radiostationnameMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.out.println("Account settings invoked");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void label_closeprogramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_closeprogramMouseClicked
        dispose();
    }//GEN-LAST:event_label_closeprogramMouseClicked

    private void label_versionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_versionMouseClicked
        //this.setUndecorated(false);
    }//GEN-LAST:event_label_versionMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_closeprogram;
    private javax.swing.JLabel label_play;
    private javax.swing.JLabel label_radiostationname;
    private javax.swing.JLabel label_version;
    // End of variables declaration//GEN-END:variables
}
