/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

/**
 *
 * @author jakubwawak
 */
public class myaccount_window extends javax.swing.JDialog {

    /**
     * Creates new form myaccount_window
     */
    public myaccount_window(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_syncpresets = new javax.swing.JLabel();
        label_loguser1 = new javax.swing.JLabel();
        label_addradio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_syncpresets.setFont(new java.awt.Font("Bodoni 72", 0, 36)); // NOI18N
        label_syncpresets.setText("Sync Presets");

        label_loguser1.setFont(new java.awt.Font("Bodoni 72", 0, 36)); // NOI18N
        label_loguser1.setText("Zaloguj");

        label_addradio.setFont(new java.awt.Font("Bodoni 72", 0, 36)); // NOI18N
        label_addradio.setText("Add Radio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(label_addradio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(label_loguser1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_syncpresets)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label_loguser1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_addradio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_syncpresets)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_addradio;
    private javax.swing.JLabel label_loguser1;
    private javax.swing.JLabel label_syncpresets;
    // End of variables declaration//GEN-END:variables
}
