/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.ontheair.Database;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Object for creating register window
 * @author jakubwawak
 */
public class register_window extends javax.swing.JDialog {

    /**
     * Creates new form register_window
     */
    Database database;
    
    /**
     * Main constructor
     * @param parent
     * @param modal
     * @param database 
     */
    public register_window(javax.swing.JDialog parent, boolean modal,Database database) {
        super(parent, modal);
        this.database = database;
        getContentPane().setBackground(Color.YELLOW);
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * Function for validate fields
     * @return boolean
     */
    boolean field_validator(){
        return !field_login.getText().equals("") && !field_login.getText().equals("Login no availble")
                && !field_name.getText().equals("") &&
                !field_password.getPassword().equals("") && !field_passwordre.getPassword().equals("");
    }
    
    /**
     * Function for checking if password is correct
     * @return boolean 
     */
    boolean password_validator(){
        if(String.valueOf(field_password.getPassword()).equals(String.valueOf(field_passwordre.getPassword()))){
            label_password.setText("Password");
            return true;
        }
        label_password.setText("Password error");
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_login = new javax.swing.JTextField();
        field_name = new javax.swing.JTextField();
        field_surname = new javax.swing.JTextField();
        field_password = new javax.swing.JPasswordField();
        field_passwordre = new javax.swing.JPasswordField();
        label_register = new javax.swing.JLabel();
        label_cancel = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        field_login.setBackground(new java.awt.Color(0, 0, 0));
        field_login.setForeground(new java.awt.Color(255, 255, 0));
        field_login.setText("login");
        field_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_loginFocusGained(evt);
            }
        });

        field_name.setBackground(new java.awt.Color(0, 0, 0));
        field_name.setForeground(new java.awt.Color(255, 255, 0));
        field_name.setText("name");
        field_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_nameFocusGained(evt);
            }
        });

        field_surname.setBackground(new java.awt.Color(0, 0, 0));
        field_surname.setForeground(new java.awt.Color(255, 255, 0));
        field_surname.setText("surname");
        field_surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_surnameFocusGained(evt);
            }
        });

        field_password.setBackground(new java.awt.Color(0, 0, 0));
        field_password.setForeground(new java.awt.Color(255, 255, 0));
        field_password.setText("password");

        field_passwordre.setBackground(new java.awt.Color(0, 0, 0));
        field_passwordre.setForeground(new java.awt.Color(255, 255, 0));
        field_passwordre.setText("password");

        label_register.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        label_register.setForeground(new java.awt.Color(0, 0, 0));
        label_register.setText("Register");
        label_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_registerMouseClicked(evt);
            }
        });

        label_cancel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        label_cancel.setForeground(new java.awt.Color(0, 0, 0));
        label_cancel.setText("Cancel");
        label_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_cancelMouseClicked(evt);
            }
        });

        label_password.setForeground(new java.awt.Color(0, 0, 0));
        label_password.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(field_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_passwordre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_password)
                        .addGap(54, 54, 54))))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_cancel)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(field_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_password)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_passwordre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_cancel)
                    .addComponent(label_register))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_cancelMouseClicked
        dispose();
    }//GEN-LAST:event_label_cancelMouseClicked

    private void field_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_nameFocusGained
        if ( field_name.getText().equals("name") )
            field_name.setText("");
        else if ( field_name.getText().equals(""))
            field_name.setText("name");
            
    }//GEN-LAST:event_field_nameFocusGained

    private void field_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_loginFocusGained
        if ( field_login.getText().equals(""))
            field_login.setText("login");
    }//GEN-LAST:event_field_loginFocusGained

    private void field_surnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_surnameFocusGained
        if ( field_surname.getText().equals("surname") )
            field_surname.setText("");
        else if ( field_surname.getText().equals(""))
            field_surname.setText("surname");
    }//GEN-LAST:event_field_surnameFocusGained

    private void label_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_registerMouseClicked
        if ( field_validator() ){
            System.out.println("All fields valid");
            if ( database.check_login_availability(field_login.getText())){
                if ( password_validator() ){
                    try {
                        if ( database.register_user(field_name.getText(), field_surname.getText(),
                                field_login.getText(),String.copyValueOf(field_password.getPassword())) == 1){
                            label_register.setText("Account created");
                            
                            field_login.setEnabled(false);
                            field_name.setEnabled(false);
                            field_surname.setEnabled(false);
                            field_password.setEnabled(false);
                            field_passwordre.setEnabled(false);
                            label_register.setEnabled(false);
                            label_cancel.setText("Close");
                        }
                        else{
                            label_register.setText("Database error");
                            field_login.setEnabled(false);
                            field_name.setEnabled(false);
                            field_surname.setEnabled(false);
                            field_password.setEnabled(false);
                            field_passwordre.setEnabled(false);
                            label_register.setEnabled(false);
                            label_cancel.setText("Close");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(register_window.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            else{
                field_login.setText("Login no availble");
            }
        }
        else{
            System.out.println("One of the fields is not valid");
        }
    }//GEN-LAST:event_label_registerMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_login;
    private javax.swing.JTextField field_name;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JPasswordField field_passwordre;
    private javax.swing.JTextField field_surname;
    private javax.swing.JLabel label_cancel;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_register;
    // End of variables declaration//GEN-END:variables
}
